<template>
  <view class="yp-page min-h-screen pb-28">
    <view :style="{ height: statusBarH + 'px' }"></view>
    <view class="px-5 pt-3 pb-3 flex items-center justify-between"><view class="size-10 rounded-full bg-white border border-black/5 flex items-center justify-center" @click="goBack"><view class="i-lucide-arrow-left text-zinc-700 text-lg"></view></view><text class="text-base font-black text-zinc-900">订单详情</text><view class="w-10"></view></view>
    <view v-if="loading" class="px-5 pt-4 space-y-4"><view class="yp-card h-40 animate-pulse bg-white/70"></view><view class="yp-card h-56 animate-pulse bg-white/70"></view></view>
    <view v-else-if="errorMessage" class="px-5 pt-24 text-center"><text class="text-sm font-black text-zinc-700 block">订单加载失败</text><text class="text-xs text-zinc-400 block mt-2">{{ errorMessage }}</text><view class="mt-4 inline-flex rounded-full bg-zinc-900 px-5 py-2 text-xs font-bold text-white" @click="loadOrder">重新加载</view></view>
    <view v-else-if="order" class="px-5 pt-4 space-y-4">
      <view class="yp-card-strong p-5"><text class="text-xl font-black text-white block">{{ statusLabel }}</text><text class="text-xs text-white/55 block mt-2">{{ statusDescription }}</text><view class="mt-5 flex items-center justify-between"><text class="text-[10px] text-white/45">{{ order.orderNo }}</text><text class="text-[10px] text-white/60">版本 {{ order.version }}</text></view></view>
      <view class="yp-card p-4"><text class="yp-section-title block mb-4">服务信息</text><view class="space-y-3"><view class="row"><text>服务内容</text><text>{{ order.serviceSnapshot?.title || order.serviceSnapshot?.packageName || '约拍服务' }}</text></view><view class="row"><text>拍摄时间</text><text>{{ formatDate(order.shootAt) }}</text></view><view class="row"><text>预计时长</text><text>{{ order.durationMinutes }} 分钟</text></view><view class="row"><text>拍摄地点</text><text>{{ locationText }}</text></view><view class="row"><text>订单备注</text><text>{{ order.remark || '无' }}</text></view></view></view>
      <view class="yp-card p-4"><text class="yp-section-title block mb-4">费用明细</text><view class="space-y-3"><view class="row"><text>服务金额</text><text>¥{{ money(order.amount) }}</text></view><view class="row"><text>平台服务费</text><text>¥{{ money(order.platformFee) }}</text></view><view class="row"><text>优惠金额</text><text class="text-emerald-600">-¥{{ money(order.discountAmount) }}</text></view><view class="h-px bg-black/5"></view><view class="flex justify-between"><text class="text-sm font-black text-zinc-900">应付金额</text><text class="text-xl font-black text-rose-500">¥{{ money(order.payableAmount) }}</text></view><view class="row"><text>支付状态</text><text>{{ paymentLabel(order.paymentStatus) }}</text></view></view></view>
      <view class="yp-card p-4"><text class="yp-section-title block mb-3">流程保障</text><view class="space-y-2"><view class="flex items-start"><view class="i-lucide-badge-dollar-sign text-emerald-500 mr-2"></view><text class="text-[10px] text-zinc-500">平台支付回调验签成功后才更新为已支付</text></view><view class="flex items-start"><view class="i-lucide-images text-emerald-500 mr-2"></view><text class="text-[10px] text-zinc-500">作品交付、修改和验收均保留版本记录</text></view><view class="flex items-start"><view class="i-lucide-star text-emerald-500 mr-2"></view><text class="text-[10px] text-zinc-500">仅完成订单可以发布一次真实评价</text></view></view></view>
    </view>
    <view v-if="order&&actions.length" class="fixed left-0 right-0 bottom-0 z-40 bg-white/95 border-t border-black/5 px-5 pt-3 pb-6 flex items-center space-x-3"><view v-for="action in actions" :key="action.label" class="flex-1 h-12 rounded-2xl flex items-center justify-center text-sm font-black" :class="action.primary?'bg-zinc-900 text-white':'border border-black/10 text-zinc-700'" @click="runAction(action)">{{ action.label }}</view></view>
  </view>
</template>
<script setup>
import { computed,getCurrentInstance,ref } from "vue";import { onLoad,onShow } from "@dcloudio/uni-app";import { getOrder,transitionOrder } from "@/api/yuepai/core";import { useUserStore } from "@/store";
const {proxy}=getCurrentInstance(),userStore=useUserStore();const statusBarH=ref(44),orderId=ref(""),order=ref(null),loading=ref(true),errorMessage=ref(""),operating=ref(false);
const statusLabel=computed(()=>({pending_payment:"等待付款",paid:"支付成功",pending_service:"等待服务",in_service:"服务进行中",pending_upload:"等待交付",pending_acceptance:"等待验收",modifying:"作品修改中",completed:"订单已完成",reviewed:"已评价",refund_requested:"退款申请中",refunding:"退款中",refunded:"已退款",cancelled:"订单已取消",dispute:"平台处理中"}[order.value?.status]||order.value?.status||"订单处理中"));const statusDescription=computed(()=>({pending_payment:"完成支付后才能锁定服务与档期",paid:"服务方确认后进入待服务",pending_service:"请按约定时间和地点履约",in_service:"双方已确认服务开始",pending_upload:"服务方需要上传交付内容",pending_acceptance:"下单用户需要检查作品并验收",modifying:"服务方根据意见重新交付",completed:"可以对本次服务发布评价",reviewed:"订单流程已结束",refund_requested:"等待平台审核退款",refunding:"退款已提交支付渠道",refunded:"退款流程已完成"}[order.value?.status]||"请关注订单后续更新"));const locationText=computed(()=>order.value?.locationSnapshot?.name||order.value?.locationSnapshot?.address||"待确认"),isBuyer=computed(()=>Number(userStore.id)===Number(order.value?.buyerUserId)),isSeller=computed(()=>Number(userStore.id)===Number(order.value?.sellerUserId));
const actions=computed(()=>{if(!order.value)return[];const s=order.value.status;if(isBuyer.value&&s==="pending_payment")return[{label:"取消订单",transition:"cancelled"},{label:"立即支付",route:"confirm",primary:true}];if(isSeller.value&&s==="paid")return[{label:"确认接单",transition:"pending_service",primary:true}];if(isSeller.value&&s==="pending_service")return[{label:"开始服务",transition:"in_service",primary:true}];if(isSeller.value&&s==="in_service")return[{label:"完成拍摄",transition:"pending_upload",primary:true}];if(isSeller.value&&["pending_upload","modifying"].includes(s))return[{label:s==="modifying"?"重新交付":"上传作品",route:"deliver",primary:true}];if(s==="pending_acceptance")return[{label:isBuyer.value?"验收作品":"查看交付",route:"deliver",primary:true}];if(isBuyer.value&&s==="completed")return[{label:"申请退款",route:"refund"},{label:"评价服务",route:"review",primary:true}];return[]});
onLoad(o=>{orderId.value=o?.id||"";try{statusBarH.value=uni.getSystemInfoSync().statusBarHeight||44}catch(e){console.warn(e)}loadOrder()});onShow(()=>{if(orderId.value)loadOrder()});async function loadOrder(){loading.value=true;errorMessage.value="";try{const r=await getOrder(orderId.value);order.value=r.data||r}catch(e){errorMessage.value=e?.message||"网络异常"}finally{loading.value=false}}
function runAction(a){if(a.route){const map={confirm:"/pages/order/confirm",deliver:"/pages/order/deliver",review:"/pages/order/review",refund:"/pages/refund/index"};return proxy.$tab.navigateTo(`${map[a.route]}?id=${orderId.value}`)}if(a.transition)uni.showModal({title:a.label,content:`确认执行“${a.label}”吗？`,success:r=>{if(r.confirm)submitTransition(a.transition)}})}async function submitTransition(toStatus){if(operating.value)return;operating.value=true;try{const r=await transitionOrder(orderId.value,{toStatus,expectedVersion:order.value.version,requestId:reqId()});order.value=r.data||r;uni.showToast({title:"状态已更新",icon:"success"})}finally{operating.value=false}}function reqId(){return`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`}function money(v){return Number(v||0).toFixed(2)}function formatDate(v){if(!v)return"待确认";const d=new Date(v);return`${d.getMonth()+1}月${d.getDate()}日 ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}function paymentLabel(v){return{unpaid:"未支付",paid:"已支付",refunded:"已退款",partial_refunded:"部分退款"}[v]||v}function goBack(){proxy.$tab.navigateBack()}
</script>
<style scoped>.row{display:flex;justify-content:space-between;gap:24rpx;font-size:22rpx;color:#a1a1aa}.row text:last-child{max-width:65%;text-align:right;color:#3f3f46}</style>
