<template>
  <view class="yp-page min-h-screen pb-28">
    <view :style="{height:statusBarH+'px'}"></view>
    <view class="px-5 pt-3 pb-3 flex items-center justify-between"><view class="size-10 rounded-full bg-white border border-black/5 flex items-center justify-center" @click="goBack"><view class="i-lucide-arrow-left text-zinc-700 text-lg"></view></view><text class="text-base font-black text-zinc-900">报价详情</text><view class="w-10"></view></view>
    <view v-if="loading" class="px-5 pt-4 space-y-4"><view class="yp-card h-40 animate-pulse bg-white/70"></view><view class="yp-card h-64 animate-pulse bg-white/70"></view></view>
    <view v-else-if="errorMessage" class="px-8 pt-24 text-center"><text class="text-base font-black text-zinc-800 block">报价加载失败</text><text class="text-xs text-zinc-400 block mt-2">{{ errorMessage }}</text><view class="mt-5 inline-flex rounded-full bg-zinc-900 px-5 py-2 text-xs font-bold text-white" @click="loadQuote">重新加载</view></view>
    <view v-else-if="quote" class="px-5 pt-4 space-y-4">
      <view class="yp-card-strong p-5"><view class="flex items-center justify-between"><text class="text-[10px] text-white/50 tracking-[3rpx]">SERVICE QUOTE</text><text class="text-[10px] font-bold" :class="statusColor">{{ statusLabel }}</text></view><text class="text-3xl font-black text-rose-300 block mt-4">¥{{ money(quote.amount) }}</text><text class="text-xs text-white/60 block mt-2">{{ quote.serviceSnapshot?.title||'约拍服务报价' }}</text><view class="mt-5 flex items-center justify-between"><text class="text-[10px] text-white/40">报价编号 {{ quote.quoteId }}</text><text class="text-[10px] text-white/40">有效期至 {{ formatDate(quote.expiresAt) }}</text></view></view>
      <view class="yp-card p-4"><text class="yp-section-title block mb-4">费用明细</text><view v-for="(value,key) in quote.feeBreakdown" :key="key" class="flex items-center justify-between py-2 border-b border-black/5 last:border-0"><text class="text-xs text-zinc-500">{{ feeLabel(key) }}</text><text class="text-xs font-bold text-zinc-700">¥{{ money(value) }}</text></view></view>
      <view class="yp-card p-4"><text class="yp-section-title block mb-4">服务快照</text><view class="space-y-3"><view class="row"><text>服务内容</text><text>{{ quote.serviceSnapshot?.description||quote.serviceSnapshot?.title||'约拍服务' }}</text></view><view class="row"><text>拍摄时间</text><text>{{ formatDate(form.shootAt) }}</text></view><view class="row"><text>预计时长</text><text>{{ duration(form.durationMinutes) }}</text></view><view class="row"><text>拍摄地点</text><text>{{ form.location }}</text></view><view class="row"><text>交付周期</text><text>{{ quote.serviceSnapshot?.deliveryDays ? quote.serviceSnapshot.deliveryDays+'天' : '按约定' }}</text></view><view class="row"><text>精修数量</text><text>{{ quote.serviceSnapshot?.retouchedCount??'按约定' }}</text></view><view class="row"><text>修改次数</text><text>{{ quote.serviceSnapshot?.revisionCount??'按约定' }}</text></view></view></view>
      <view v-if="quote.remark" class="yp-card p-4"><text class="yp-section-title block mb-3">补充说明</text><text class="text-xs text-zinc-500 leading-relaxed whitespace-pre-wrap">{{ quote.remark }}</text></view>
      <view v-if="canAccept" class="yp-card p-4 space-y-3"><text class="yp-section-title block">确认订单信息</text><view><text class="form-label">拍摄时间</text><input v-model="form.shootAt" class="form-input" placeholder="2026-07-01T14:00:00" /></view><view><text class="form-label">拍摄地点</text><input v-model.trim="form.location" class="form-input" placeholder="城市和详细地址" /></view><view class="grid grid-cols-2 gap-3"><view><text class="form-label">联系人</text><input v-model.trim="form.contactName" class="form-input" /></view><view><text class="form-label">手机号</text><input v-model.trim="form.contactPhone" type="number" maxlength="11" class="form-input" /></view></view></view>
      <view class="rounded-2xl bg-amber-50 p-4 flex items-start"><view class="i-lucide-shield-check text-amber-600 mr-3"></view><text class="text-[10px] text-amber-700 leading-relaxed">接受报价后会生成待支付订单，服务内容和价格写入不可变快照。支付前仍可按规则取消。</text></view>
    </view>
    <view v-if="quote&&actionsVisible" class="fixed left-0 right-0 bottom-0 z-40 bg-white/95 border-t border-black/5 px-5 pt-3 pb-6 flex items-center space-x-3"><view v-if="canReject" class="flex-1 h-12 rounded-2xl border border-black/10 flex items-center justify-center text-sm font-black text-zinc-700" @click="rejectCurrent">拒绝</view><view v-if="canWithdraw" class="flex-1 h-12 rounded-2xl border border-black/10 flex items-center justify-center text-sm font-black text-zinc-700" @click="withdrawCurrent">撤回</view><view v-if="canAccept" class="flex-[2] h-12 rounded-2xl bg-zinc-900 text-white flex items-center justify-center text-sm font-black" @click="acceptCurrent">接受并生成订单</view></view>
  </view>
</template>
<script setup>
import { computed,getCurrentInstance,reactive,ref } from "vue";import { onLoad } from "@dcloudio/uni-app";import request from "@/utils/request";import { useUserStore } from "@/store";import { acceptQuote } from "@/api/yuepai/core";import { getQuote } from "@/api/yuepai/quote-query";
const {proxy}=getCurrentInstance(),userStore=useUserStore();const statusBarH=ref(44),quoteId=ref(""),quote=ref(null),loading=ref(true),errorMessage=ref(""),operating=ref(false);const form=reactive({shootAt:"",durationMinutes:120,location:"",contactName:"",contactPhone:""});
const isReceiver=computed(()=>Number(userStore.id)===Number(quote.value?.receiverUserId)),isSender=computed(()=>Number(userStore.id)===Number(quote.value?.senderUserId)),pending=computed(()=>["pending","negotiating"].includes(quote.value?.status)),canAccept=computed(()=>isReceiver.value&&pending.value),canReject=computed(()=>isReceiver.value&&pending.value),canWithdraw=computed(()=>isSender.value&&pending.value),actionsVisible=computed(()=>canAccept.value||canReject.value||canWithdraw.value),statusLabel=computed(()=>({pending:"待处理",negotiating:"议价中",accepted:"已接受",rejected:"已拒绝",withdrawn:"已撤回",expired:"已过期"}[quote.value?.status]||quote.value?.status)),statusColor=computed(()=>quote.value?.status==="accepted"?"text-emerald-300":pending.value?"text-amber-300":"text-white/50");
onLoad(o=>{quoteId.value=o?.id||"";try{statusBarH.value=uni.getSystemInfoSync().statusBarHeight||44}catch(e){console.warn(e)}loadQuote()});async function loadQuote(){loading.value=true;errorMessage.value="";try{const r=await getQuote(quoteId.value);quote.value=r.data||r;const s=quote.value.serviceSnapshot||{};form.shootAt=s.proposedShootAt||"";form.durationMinutes=Number(s.durationMinutes||120);form.location=s.proposedLocation||"";form.contactName=s.contact?.name||"";form.contactPhone=s.contact?.phone||""}catch(e){errorMessage.value=e?.message||"网络异常"}finally{loading.value=false}}
async function acceptCurrent(){if(operating.value)return;if(!form.shootAt||!form.location.trim()||!form.contactName.trim()||!/^1\d{10}$/.test(form.contactPhone))return uni.showToast({title:"请完整填写订单信息",icon:"none"});operating.value=true;try{const r=await acceptQuote(quoteId.value,{requestId:reqId(),shootAt:new Date(form.shootAt).toISOString(),durationMinutes:Number(form.durationMinutes),locationSnapshot:{name:form.location.trim()},contactSnapshot:{name:form.contactName.trim(),phone:form.contactPhone},remark:quote.value.remark||null});const order=r.data||r;uni.showModal({title:"订单已创建",content:"请在订单中心完成后续支付和履约。",showCancel:false,success(){proxy.$tab.redirectTo(`/pages/order/detail?id=${order.orderId}`)}})}finally{operating.value=false}}
function rejectCurrent(){changeStatus("reject","确认拒绝该报价吗？")}function withdrawCurrent(){changeStatus("withdraw","确认撤回该报价吗？")}function changeStatus(action,content){uni.showModal({title:action==="reject"?"拒绝报价":"撤回报价",content,success:async r=>{if(!r.confirm)return;await request({url:`/yuepai/quotes/${quoteId.value}/${action}`,method:"post",data:{expectedVersion:quote.value.version,reason:action==="reject"?"暂不接受该报价":"发送方主动撤回"}});await loadQuote()}})}function reqId(){return`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`}function feeLabel(k){return({service:"服务费",shooting:"拍摄费",makeup:"妆造费",venue:"场地费",transport:"交通费"}[k]||k)}function money(v){return Number(v||0).toFixed(2)}function duration(v){return Number(v)>=60?`${Math.round(Number(v)/60)}小时`:`${v}分钟`}function formatDate(v){if(!v)return"待确认";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}function goBack(){proxy.$tab.navigateBack()}
</script>
<style scoped>.row{display:flex;justify-content:space-between;gap:24rpx;font-size:22rpx;color:#71717a}.row text:last-child{max-width:65%;text-align:right;color:#3f3f46}.form-label{display:block;margin-bottom:10rpx;font-size:20rpx;font-weight:700;color:#52525b}.form-input{width:100%;height:84rpx;padding:0 24rpx;border-radius:24rpx;background:#fafafa;font-size:24rpx}</style>
